const studentNav=[['dashboard','⌂','Dashboard'],['rooster','▦','Rooster'],['huiswerk','✓','Huiswerk'],['toetsen','◫','Toetsen'],['cijfers','★','Cijfers'],['absenties','◌','Absenties'],['vakken','◆','Vakken'],['berichten','✉','Berichten'],['bestanden','▤','Bestanden'],['profiel','◎','Profiel'],['instellingen','⚙','Instellingen']];
const teacherNav=[['dashboard','⌂','Dashboard'],['rooster','▦','Mijn rooster'],['klassen','♟','Klassen'],['aanwezigheid','✓','Aanwezigheid'],['opdrachten','▤','Opdrachten'],['cijfers','★','Cijfers invoeren'],['berichten','✉','Berichten'],['bestanden','▤','Bestanden'],['profiel','◎','Profiel'],['instellingen','⚙','Instellingen']];
const lessons=[
{time:'08:30 – 09:20',subject:'Nederlands',room:'B1.14',teacher:'Mevr. De Vries',className:'3M2',color:'purple'},
{time:'09:20 – 10:10',subject:'Wiskunde',room:'A2.08',teacher:'Dhr. Jansen',className:'2K1',color:'blue'},
{time:'10:30 – 11:20',subject:'Engels',room:'C0.03',teacher:'Mevr. Bakker',className:'3M1',color:'green'},
{time:'11:20 – 12:10',subject:'Biologie',room:'B2.21',teacher:'Dhr. Smit',className:'4M2',color:'orange'},
{time:'13:00 – 13:50',subject:'Geschiedenis',room:'A1.11',teacher:'Mevr. Vos',className:'3M2',color:'red'}];
const defaultState={role:'leerling',page:'dashboard',dark:false,homework:[
{id:1,subject:'Nederlands',title:'Lees hoofdstuk 4 en maak opdracht 12 t/m 18',due:'Morgen',done:false},
{id:2,subject:'Wiskunde',title:'§3.4 opdrachten 21, 22, 25 en 27',due:'Vrijdag',done:false},
{id:3,subject:'Engels',title:'Learn vocabulary Unit 2',due:'Maandag',done:true},
{id:4,subject:'Biologie',title:'Werkblad cellen afronden',due:'Dinsdag',done:false}],
grades:[['Wiskunde','Toets algebra',8.1,3],['Engels','Vocabulary Unit 1',8.3,1],['Nederlands','Leesvaardigheid',7.4,2],['Biologie','Cellen',7.8,2],['Geschiedenis','Middeleeuwen',6.9,2],['Wiskunde','SO hoofdstuk 2',6.4,1]],
attendance:{},messages:[{from:'Mevr. De Vries',text:'Vergeet morgen je leesboek niet mee te nemen.',time:'16:42'},{from:'Dhr. Jansen',text:'De uitwerkingen van hoofdstuk 3 staan online.',time:'Gisteren'},{from:'Schooladministratie',text:'Nieuwe informatie over de studiedag.',time:'Maandag'}],assignments:[{id:1,title:'Boekverslag',className:'3M2',due:'28 aug',submitted:12,total:26},{id:2,title:'Grammatica hoofdstuk 2',className:'2K1',due:'31 aug',submitted:17,total:25}],settings:{notifications:true,email:false,compact:false}};
let state=Object.assign({},defaultState,JSON.parse(localStorage.getItem('schoolportal-state')||'{}'));
if(!state.homework) state.homework=defaultState.homework;if(!state.grades) state.grades=defaultState.grades;if(!state.messages) state.messages=defaultState.messages;if(!state.assignments) state.assignments=defaultState.assignments;if(!state.attendance) state.attendance={};if(!state.settings) state.settings=defaultState.settings;
const $=s=>document.querySelector(s);const content=$('#content'),nav=$('#nav');
function save(){localStorage.setItem('schoolportal-state',JSON.stringify(state))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1900)}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(n){return Number(n).toFixed(1).replace('.',',')}
function average(){const w=state.grades.reduce((a,g)=>a+(Number(g[2])*Number(g[3])),0),d=state.grades.reduce((a,g)=>a+Number(g[3]),0);return d?fmt(w/d):'-'}
function pageHeader(title,sub,action=''){return `<div class="page-title"><div><h2>${title}</h2><p>${sub}</p></div>${action}</div>`}
function card(title,body,action=''){return `<section class="card"><div class="card-head"><h3>${title}</h3>${action}</div>${body}</section>`}
function stat(label,value,hint){return `<div class="stat"><span>${label}</span><b>${value}</b><small>${hint}</small></div>`}
function setRole(role){state.role=role;state.page='dashboard';save();render();toast(`Gewisseld naar ${role}`)}
function setPage(page){state.page=page;save();render();window.scrollTo({top:0,behavior:'smooth'})}
window.setPage=setPage;window.setRole=setRole;
function renderNav(){const items=state.role==='leerling'?studentNav:teacherNav;nav.innerHTML=items.map(([id,icon,label])=>`<button class="nav-btn ${state.page===id?'active':''}" onclick="setPage('${id}')"><span>${icon}</span>${label}</button>`).join('');document.querySelectorAll('[data-role]').forEach(b=>b.classList.toggle('selected',b.dataset.role===state.role));$('#portalLabel').textContent=state.role==='leerling'?'Leerlingportaal':'Docentenportaal';$('#avatar').textContent=state.role==='leerling'?'LW':'JD';$('#pageTitle').textContent=(items.find(x=>x[0]===state.page)||items[0])[2]}
function render(){document.querySelector('#app').classList.toggle('dark',!!state.dark);$('#themeBtn').textContent=state.dark?'☀':'☾';renderNav();const fn=pages[state.page]||pages.dashboard;content.innerHTML=fn();bindPage();}
function heroTeacher(){return `<div class="hero teacher"><div><span class="eyebrow">✦ Woensdag 26 augustus</span><h2>Goedemiddag, meneer De Jong</h2><p>Vandaag geef je 5 lessen aan 4 verschillende klassen.</p></div><div class="hero-orb">♟</div></div>`}
function heroStudent(){return `<div class="hero"><div><span class="eyebrow">✦ Woensdag 26 augustus</span><h2>Goedemiddag, Levi</h2><p>Je hebt vandaag nog 3 lessen en ${state.homework.filter(h=>!h.done).length} openstaande taken.</p></div><div class="hero-orb">◆</div></div>`}
function lessonList(){return `<div class="timeline">${lessons.map((l,i)=>`<div class="lesson"><div>${l.time.split(' – ')[0]}</div><div class="bar ${l.color}"></div><div><strong>${state.role==='docent'?l.className+' · ':''}${l.subject}</strong><span>${l.room} · ${state.role==='docent'?25+i+' leerlingen':l.teacher}</span></div>${i===2?'<span class="badge">VOLGENDE</span>':''}</div>`).join('')}</div>`}
const pages={
dashboard(){if(state.role==='docent') return heroTeacher()+`<div class="stats">${stat('Lessen vandaag','5','Eerste om 08:30')}${stat('Na te kijken','23','3 opdrachten')}${stat('Mentorleerlingen','26','Klas 3M2')}${stat('Ongelezen','4','Nieuwe berichten')}</div><div class="grid2">${card('Mijn lessen',lessonList(),'<button class="link-btn" onclick="setPage(\'rooster\')">Rooster</button>')}${card('Snelle acties',`<div class="quick-grid"><button onclick="setPage('aanwezigheid')"><b>✓ Aanwezigheid</b><span>Registreren</span></button><button onclick="setPage('cijfers')"><b>★ Cijfers</b><span>Invoeren</span></button><button onclick="openAssignmentModal()"><b>＋ Opdracht</b><span>Aanmaken</span></button><button onclick="setPage('berichten')"><b>✉ Bericht</b><span>Versturen</span></button></div>`)}</div>`;
return heroStudent()+`<div class="stats">${stat('Gemiddelde',average(),'+0,2 deze periode')}${stat('Open huiswerk',state.homework.filter(h=>!h.done).length,state.homework.filter(h=>h.done).length+' afgerond')}${stat('Aanwezigheid','97%','Dit schooljaar')}${stat('Volgende toets','4 d','Wiskunde · Algebra')}</div><div class="grid2">${card('Vandaag',lessonList(),'<button class="link-btn" onclick="setPage(\'rooster\')">Volledig rooster</button>')}${card('Huiswerk',homeworkList(3),'<button class="link-btn" onclick="setPage(\'huiswerk\')">Alles bekijken</button>')}</div><div class="grid2">${card('Laatste cijfers',gradeList(4),'<button class="link-btn" onclick="setPage(\'cijfers\')">Cijferoverzicht</button>')}${card('Berichten',messagePreview(),'<button class="link-btn" onclick="setPage(\'berichten\')">Inbox openen</button>')}</div>`},
rooster(){const days=['Maandag','Dinsdag','Woensdag','Donderdag','Vrijdag'];const rows=['08:30','09:20','10:30','11:20','13:00'];return pageHeader('Rooster',state.role==='docent'?'Je lessen en lokalen voor deze week.':'Je lesrooster voor deze week.')+card('Week 35',`<div class="schedule-wrap"><div class="schedule-grid"><div class="head"></div>${days.map(d=>`<div class="head">${d}</div>`).join('')}${rows.map((t,r)=>`<div class="timecell">${t}</div>${days.map((d,c)=>{const l=lessons[(r+c)%lessons.length];return `<div class="schedule-item"><b>${state.role==='docent'?l.className:l.subject}</b><br>${state.role==='docent'?l.subject:l.room}<br><small>${l.room}</small></div>`}).join('')}`).join('')}</div></div>`)},
huiswerk(){return pageHeader('Huiswerk','Bekijk en beheer je openstaande taken.')+card('Alle taken',homeworkList())},
toetsen(){return pageHeader('Toetsen','Aankomende toetsen en deadlines.')+`<div class="grid3">${[['Wiskunde','Toets algebra','30 augustus','×3'],['Engels','Vocabulary Unit 2','2 september','×1'],['Biologie','Practicum cellen','5 september','×2']].map(t=>card(t[0],`<div class="list"><div class="list-row"><div class="grow"><strong>${t[1]}</strong><span>${t[2]}</span></div><span class="badge">weging ${t[3]}</span></div><button class="soft-btn" onclick="toast('Herinnering ingesteld')">Herinner mij</button></div>`)).join('')}</div>`},
cijfers(){return state.role==='docent'?teacherGradesPage():pageHeader('Cijfers',`Je gewogen gemiddelde is ${average()}.`)+`<div class="stats">${stat('Gemiddelde',average(),'Alle vakken')}${stat('Hoogste','8,3','Engels')}${stat('Cijfers',state.grades.length,'Dit schooljaar')}${stat('Voldoendes',Math.round(state.grades.filter(g=>g[2]>=5.5).length/state.grades.length*100)+'%','Percentage')}</div>${card('Alle cijfers',gradeList())}`},
absenties(){return pageHeader('Absenties','Overzicht van aanwezigheid, te laat en meldingen.',`<button class="primary-btn" onclick="openAbsenceModal()">Ziekmelding</button>`)+`<div class="stats">${stat('Aanwezig','97%','Dit schooljaar')}${stat('Te laat','2','Registraties')}${stat('Geoorloofd','3 uur','Absent')}${stat('Ongeoorloofd','0','Geen meldingen')}</div>${card('Registraties',`<div class="list"><div class="list-row"><span class="badge yellow">TE LAAT</span><div class="grow"><strong>Wiskunde</strong><span>12 augustus · 09:27 · 7 minuten</span></div></div><div class="list-row"><span class="badge green">GEOORLOOFD</span><div class="grow"><strong>Tandarts</strong><span>4 juli · 10:30 – 12:10</span></div></div></div>`)}`},
vakken(){return pageHeader('Vakken','Je vakken, docenten en voortgang.')+`<div class="grid3">${[['Nederlands','Mevr. De Vries','7,4'],['Wiskunde','Dhr. Jansen','7,3'],['Engels','Mevr. Bakker','8,3'],['Biologie','Dhr. Smit','7,8'],['Geschiedenis','Mevr. Vos','6,9'],['LO','Dhr. Peeters','V']].map(v=>card(v[0],`<div class="list-row"><div class="grow"><strong>${v[1]}</strong><span>3M2 · 3 lessen per week</span></div><span class="grade ${Number(v[2].replace(',','.'))>=7.5?'high':''}">${v[2]}</span></div><button class="soft-btn" onclick="toast('Vak geopend')">Open vak</button>`)).join('')}</div>`},
berichten(){return messagePage()},
bestanden(){return pageHeader('Bestanden','Lesmateriaal en gedeelde documenten.',`<button class="primary-btn" onclick="openFileModal()">Bestand toevoegen</button>`)+card('Bestanden',`<div class="list">${[['PDF','Uitwerkingen hoofdstuk 3','Wiskunde · 2,1 MB'],['DOC','Boekverslag voorbeeld','Nederlands · 840 KB'],['PPT','Cellen en weefsels','Biologie · 4,8 MB'],['PDF','Studiewijzer periode 1','School · 1,4 MB']].map(f=>`<div class="list-row"><span class="badge">${f[0]}</span><div class="grow"><strong>${f[1]}</strong><span>${f[2]}</span></div><button class="soft-btn" onclick="toast('Demo-bestand geopend')">Open</button></div>`).join('')}</div>`)},
profiel(){return pageHeader('Profiel','Je account- en schoolgegevens.')+`<div class="grid2">${card('Persoonlijke gegevens',`<div class="form-grid"><div class="field"><label>Naam</label><input value="${state.role==='docent'?'J. de Jong':'Levi Wassink'}"></div><div class="field"><label>Rol</label><input value="${state.role==='docent'?'Docent':'Leerling'}" disabled></div><div class="field"><label>E-mail</label><input value="${state.role==='docent'?'j.dejong@school.nl':'levi@school.nl'}"></div><div class="field"><label>${state.role==='docent'?'Mentorklas':'Klas'}</label><input value="3M2" disabled></div><div class="field full"><button class="primary-btn" onclick="toast('Profiel lokaal opgeslagen')">Opslaan</button></div></div>`)}${card('Schoolgegevens',`<div class="list"><div class="list-row"><div class="grow"><strong>Delta College</strong><span>Schooljaar 2026–2027</span></div></div><div class="list-row"><div class="grow"><strong>${state.role==='docent'?'Personeelsnummer':'Leerlingnummer'}</strong><span>${state.role==='docent'?'D-1042':'20263184'}</span></div></div></div>`)}</div>`},
instellingen(){return pageHeader('Instellingen','Pas je portaal aan.')+card('Weergave & meldingen',settingsRows())},
klassen(){return pageHeader('Klassen','Bekijk je klassen en leerlingen.')+`<div class="grid3">${[['3M2',26,'Mentorklas'],['2K1',25,'Nederlands'],['3M1',27,'Nederlands'],['4M2',24,'Nederlands']].map(c=>card(c[0],`<div class="list-row"><div class="grow"><strong>${c[1]} leerlingen</strong><span>${c[2]}</span></div><span class="badge green">ACTIEF</span></div><button class="soft-btn" onclick="setPage('aanwezigheid')">Open klas</button>`)).join('')}</div>`},
aanwezigheid(){return attendancePage()},
opdrachten(){return assignmentsPage()}
};
function homeworkList(limit){const arr=limit?state.homework.slice(0,limit):state.homework;return `<div class="list">${arr.map(h=>`<div class="list-row"><button class="check ${h.done?'done':''}" data-homework="${h.id}">${h.done?'✓':''}</button><div class="grow ${h.done?'done-text':''}"><strong>${esc(h.subject)}</strong><span>${esc(h.title)}</span></div><span class="badge ${h.done?'green':''}">${h.done?'KLAAR':esc(h.due)}</span></div>`).join('')}</div>`}
function gradeList(limit){const arr=limit?state.grades.slice(0,limit):state.grades;return `<div class="list">${arr.map(g=>`<div class="list-row"><div class="grow"><strong>${esc(g[0])}</strong><span>${esc(g[1])} · weging ×${g[3]}</span></div><span class="grade ${g[2]>=7.5?'high':''}">${fmt(g[2])}</span></div>`).join('')}</div>`}
function messagePreview(){return `<div class="list">${state.messages.slice(0,3).map(m=>`<div class="list-row"><div class="avatar">${esc(m.from[0])}</div><div class="grow"><strong>${esc(m.from)}</strong><span>${esc(m.text)}</span></div><small>${esc(m.time)}</small></div>`).join('')}</div>`}
function messagePage(){const first=state.messages[0];return pageHeader('Berichten','Communiceer met docenten, leerlingen en school.',`<button class="primary-btn" onclick="openMessageModal()">Nieuw bericht</button>`)+`<div class="message-layout"><div class="message-list">${state.messages.map((m,i)=>`<div class="message-item ${i===0?'active':''}"><strong>${esc(m.from)}</strong><span>${esc(m.text)}</span></div>`).join('')}</div><div class="chat"><div class="chat-body"><h3>${esc(first.from)}</h3><div class="bubble">${esc(first.text)}</div><div class="bubble mine">Bedankt, ik heb het gezien.</div></div><div class="composer"><input id="chatInput" placeholder="Typ een bericht..."><button id="sendChat" class="primary-btn">Verstuur</button></div></div></div>`}
function teacherGradesPage(){return pageHeader('Cijfers invoeren','Voeg cijfers toe voor je leerlingen.',`<button class="primary-btn" onclick="openGradeModal()">Nieuw cijfer</button>`)+`<div class="grid2">${card('Recente invoer',gradeList())}${card('Snel invoeren',`<div class="form-grid"><div class="field"><label>Klas</label><select id="quickClass"><option>3M2</option><option>2K1</option><option>3M1</option></select></div><div class="field"><label>Onderdeel</label><input id="quickTitle" value="Leesvaardigheid"></div><div class="field"><label>Cijfer</label><input id="quickGrade" type="number" min="1" max="10" step="0.1" value="7.5"></div><div class="field"><label>Weging</label><input id="quickWeight" type="number" min="1" max="5" value="1"></div><div class="field full"><button id="quickGradeBtn" class="primary-btn">Cijfer opslaan</button></div></div>`)}</div>`}
function attendancePage(){const names=['Daan Jansen','Sophie de Vries','Milan Smit','Noa Bakker','Finn Vos','Emma Peters','Lucas Meijer','Lotte Bos'];return pageHeader('Aanwezigheid','Klas 3M2 · Nederlands · 08:30',`<button class="primary-btn" id="saveAttendance">Registratie opslaan</button>`)+card('Leerlingen',`<div class="schedule-wrap"><table class="student-table"><thead><tr><th>Leerling</th><th>Status</th></tr></thead><tbody>${names.map((n,i)=>`<tr><td><strong>${n}</strong><br><small>#${202600+i+1}</small></td><td><div class="presence" data-student="${i}"><button data-status="ok" class="${state.attendance[i]==='ok'?'active ok':''}">Aanwezig</button><button data-status="late" class="${state.attendance[i]==='late'?'active late':''}">Te laat</button><button data-status="no" class="${state.attendance[i]==='no'?'active no':''}">Afwezig</button></div></td></tr>`).join('')}</tbody></table></div>`) }
function assignmentsPage(){return pageHeader('Opdrachten','Maak opdrachten en bekijk inleverstatus.',`<button class="primary-btn" onclick="openAssignmentModal()">Nieuwe opdracht</button>`)+`<div class="grid3">${state.assignments.map(a=>card(esc(a.title),`<div class="list-row"><div class="grow"><strong>${esc(a.className)}</strong><span>Deadline ${esc(a.due)}</span></div><span class="badge">${a.submitted}/${a.total}</span></div><button class="soft-btn" onclick="toast('Opdracht geopend')">Nakijken</button>`)).join('')}</div>`}
function settingsRows(){return `<div class="settings-row"><div><strong>Donkere modus</strong><br><small>Gebruik een donker kleurenschema</small></div><div class="switch ${state.dark?'on':''}" data-setting="dark"><i></i></div></div><div class="settings-row"><div><strong>Pushmeldingen</strong><br><small>Nieuwe cijfers en berichten</small></div><div class="switch ${state.settings.notifications?'on':''}" data-setting="notifications"><i></i></div></div><div class="settings-row"><div><strong>E-mailmeldingen</strong><br><small>Ontvang belangrijke updates per mail</small></div><div class="switch ${state.settings.email?'on':''}" data-setting="email"><i></i></div></div><div class="settings-row"><div><strong>Compacte weergave</strong><br><small>Minder ruimte tussen onderdelen</small></div><div class="switch ${state.settings.compact?'on':''}" data-setting="compact"><i></i></div></div>`}
function bindPage(){document.querySelectorAll('[data-homework]').forEach(b=>b.onclick=()=>{const h=state.homework.find(x=>x.id==b.dataset.homework);h.done=!h.done;save();render();toast(h.done?'Huiswerk afgerond':'Taak opnieuw geopend')});document.querySelectorAll('.presence button').forEach(b=>b.onclick=()=>{const p=b.closest('.presence');state.attendance[p.dataset.student]=b.dataset.status;save();render()});const sa=$('#saveAttendance');if(sa)sa.onclick=()=>toast('Aanwezigheid opgeslagen');const q=$('#quickGradeBtn');if(q)q.onclick=()=>{const grade=Number($('#quickGrade').value),weight=Number($('#quickWeight').value);if(!grade||grade<1||grade>10)return toast('Vul een geldig cijfer in');state.grades.unshift([$('#quickClass').value,$('#quickTitle').value||'Onderdeel',grade,weight||1]);save();render();toast('Cijfer opgeslagen')};const send=$('#sendChat');if(send)send.onclick=()=>{const inp=$('#chatInput');if(inp.value.trim()){state.messages.unshift({from:state.role==='docent'?'Levi Wassink':'Meneer De Jong',text:inp.value.trim(),time:'Nu'});save();render();toast('Bericht verstuurd')}};document.querySelectorAll('[data-setting]').forEach(s=>s.onclick=()=>{const k=s.dataset.setting;if(k==='dark')state.dark=!state.dark;else state.settings[k]=!state.settings[k];save();render()})}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').showModal()}
window.openGradeModal=()=>openModal(`<h2>Nieuw cijfer</h2><div class="form-grid"><div class="field"><label>Vak</label><select id="mgSubject"><option>Nederlands</option><option>Wiskunde</option><option>Engels</option></select></div><div class="field"><label>Onderdeel</label><input id="mgTitle" placeholder="Bijv. Toets hoofdstuk 3"></div><div class="field"><label>Cijfer</label><input id="mgGrade" type="number" min="1" max="10" step="0.1"></div><div class="field"><label>Weging</label><input id="mgWeight" type="number" value="1" min="1" max="5"></div><div class="field full"><button class="primary-btn" onclick="saveGradeModal()">Opslaan</button></div></div>`);
window.saveGradeModal=()=>{const g=Number($('#mgGrade').value);if(g<1||g>10)return toast('Ongeldig cijfer');state.grades.unshift([$('#mgSubject').value,$('#mgTitle').value||'Nieuw onderdeel',g,Number($('#mgWeight').value)||1]);save();$('#modal').close();render();toast('Cijfer toegevoegd')};
window.openAssignmentModal=()=>openModal(`<h2>Nieuwe opdracht</h2><div class="form-grid"><div class="field"><label>Titel</label><input id="maTitle" placeholder="Bijv. Boekverslag"></div><div class="field"><label>Klas</label><select id="maClass"><option>3M2</option><option>2K1</option><option>3M1</option><option>4M2</option></select></div><div class="field"><label>Deadline</label><input id="maDue" type="date"></div><div class="field full"><label>Beschrijving</label><textarea placeholder="Opdrachtomschrijving"></textarea></div><div class="field full"><button class="primary-btn" onclick="saveAssignmentModal()">Opdracht maken</button></div></div>`);
window.saveAssignmentModal=()=>{const title=$('#maTitle').value.trim();if(!title)return toast('Vul een titel in');state.assignments.unshift({id:Date.now(),title,className:$('#maClass').value,due:$('#maDue').value||'Geen datum',submitted:0,total:26});save();$('#modal').close();state.page='opdrachten';render();toast('Opdracht aangemaakt')};
window.openMessageModal=()=>openModal(`<h2>Nieuw bericht</h2><div class="form-grid"><div class="field full"><label>Aan</label><input id="mmTo" placeholder="Naam ontvanger"></div><div class="field full"><label>Bericht</label><textarea id="mmText" placeholder="Schrijf je bericht..."></textarea></div><div class="field full"><button class="primary-btn" onclick="saveMessageModal()">Versturen</button></div></div>`);
window.saveMessageModal=()=>{const to=$('#mmTo').value.trim(),text=$('#mmText').value.trim();if(!to||!text)return toast('Vul ontvanger en bericht in');state.messages.unshift({from:to,text,time:'Nu'});save();$('#modal').close();render();toast('Bericht verstuurd')};
window.openAbsenceModal=()=>openModal(`<h2>Ziekmelding</h2><div class="form-grid"><div class="field"><label>Van</label><input type="date"></div><div class="field"><label>Tot</label><input type="date"></div><div class="field full"><label>Opmerking</label><textarea placeholder="Optionele toelichting"></textarea></div><div class="field full"><button class="primary-btn" onclick="document.querySelector('#modal').close();toast('Ziekmelding lokaal opgeslagen')">Melden</button></div></div>`);
window.openFileModal=()=>openModal(`<h2>Bestand toevoegen</h2><p>GitHub Pages heeft geen serveropslag. Deze demo kan daarom geen echte privébestanden uploaden.</p><div class="field"><label>Bestandsnaam</label><input placeholder="Naam van bestand"></div><br><button class="primary-btn" onclick="document.querySelector('#modal').close();toast('Demo-item toegevoegd')">Toevoegen</button>`);
$('#themeBtn').onclick=()=>{state.dark=!state.dark;save();render()};$('#menuBtn').onclick=()=>{$('#sidebar').classList.add('open');$('#scrim').classList.add('show')};$('#scrim').onclick=()=>{$('#sidebar').classList.remove('open');$('#scrim').classList.remove('show')};document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>setRole(b.dataset.role));$('#logoutBtn').onclick=()=>toast('Demo-modus: er is geen echte login nodig');$('#searchInput').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.list-row,.card').forEach(el=>{const hit=el.textContent.toLowerCase().includes(q);if(q.length>1)el.style.opacity=hit?'1':'.28';else el.style.opacity='1'})});
render();