/* SchoolPortal V3 — application controller and interactions */
(() => {
  const SP=window.SP, U=SP.ui;
  const {$,$$,esc,toast,modal,field,selectField,textareaField,form,saveAndRender,confirmAction,download,studentName,className,nextNumber}=U;

  const App={
    render(){
      document.documentElement.dataset.theme=SP.state.theme;
      document.documentElement.dataset.accent=SP.state.accent;
      const root=$('#app');
      if(!root) return;
      root.innerHTML=SP.state.role==='teacher'?SP.teacher.shell():SP.student.shell();
      if(SP.state.role==='teacher') $('#teacherView').innerHTML=SP.teacher.render();
      else $('#studentView').innerHTML=SP.student.render();
      bind();
    },
    goStudent(page){SP.state.studentPage=page;SP.save();App.render();window.scrollTo({top:0,behavior:'smooth'})},
    goTeacher(page){SP.state.teacherPage=page;SP.save();App.render();window.scrollTo({top:0,behavior:'smooth'})},
    switchRole(role){SP.state.role=role;SP.save();App.render();toast(role==='teacher'?'Docentenomgeving geopend':'Leerlingomgeving geopend')}
  };
  window.SPApp=App;

  function bind(){
    $$('[data-student-page]').forEach(b=>b.onclick=()=>App.goStudent(b.dataset.studentPage));
    $$('[data-teacher-page]').forEach(b=>b.onclick=()=>App.goTeacher(b.dataset.teacherPage));
    $$('[data-switch-role]').forEach(b=>b.onclick=()=>App.switchRole(b.dataset.switchRole));
    $$('[data-student-theme],[data-teacher-theme]').forEach(b=>b.onclick=toggleTheme);
    $$('[data-student-menu]').forEach(b=>b.onclick=openStudentMenu);
    $('[data-student-search]')?.addEventListener('click',openStudentSearch);
    $('[data-student-message-form]')?.addEventListener('submit',sendStudentMessage);
    $$('[data-conversation]').forEach(b=>b.onclick=()=>{SP.state.selectedConversationId=b.dataset.conversation;SP.save();App.render()});
    $$('[data-homework-toggle]').forEach(b=>b.onclick=()=>toggleHomework(b.dataset.homeworkToggle));
    $$('[data-lesson-info]').forEach(b=>b.onclick=()=>openLessonInfo(b.dataset.lessonInfo));

    $('[data-command]')?.addEventListener('click',openCommandPalette);
    $('[data-quick-create]')?.addEventListener('click',openQuickCreate);
    $('[data-teacher-mobile]')?.addEventListener('click',()=>$('.teacher-rail')?.classList.add('mobile-open'));
    $('[data-teacher-scrim]')?.addEventListener('click',()=>$('.teacher-rail')?.classList.remove('mobile-open'));
    $('[data-teacher-menu]')?.addEventListener('click',openTeacherMenu);

    $$('[data-create-student]').forEach(b=>b.onclick=()=>openStudentEditor());
    $$('[data-open-student]').forEach(b=>b.onclick=()=>openStudentDrawer(b.dataset.openStudent));
    $$('[data-student-actions]').forEach(b=>b.onclick=()=>openStudentActions(b.dataset.studentActions));
    $('[data-student-filter]')?.addEventListener('input',filterStudentTable);
    $('[data-class-filter]')?.addEventListener('change',e=>{SP.state.selectedClassId=e.target.value;SP.save();App.render()});
    $$('[data-select-class]').forEach(b=>b.onclick=()=>{SP.state.selectedClassId=b.dataset.selectClass;SP.save()});
    $$('[data-edit-class]').forEach(b=>b.onclick=()=>openClassEditor(b.dataset.editClass));
    $$('[data-create-class]').forEach(b=>b.onclick=()=>openClassEditor());
    $$('[data-export-students]').forEach(b=>b.onclick=exportStudents);
    $$('[data-import-students]').forEach(b=>b.onclick=openImportStudents);

    $$('[data-new-lesson]').forEach(b=>b.onclick=()=>openLessonEditor());
    $$('[data-edit-lesson]').forEach(b=>b.onclick=()=>openLessonEditor(b.dataset.editLesson));
    $$('[data-slot-add]').forEach(b=>b.onclick=()=>{const [day,time]=b.dataset.slotAdd.split('|');openLessonEditor(null,{day:Number(day),start:time})});
    bindDragDrop();
    $$('[data-schedule-template]').forEach(b=>b.onclick=()=>toast('Weekindeling staat klaar om te kopiëren','success'));

    $$('[data-set-attendance]').forEach(b=>b.onclick=handleAttendanceButton);
    $$('[data-mark-all-present]').forEach(b=>b.onclick=markAllPresent);
    $$('[data-save-attendance]').forEach(b=>b.onclick=()=>{SP.audit('Presentie voor les 3M2 afgesloten');toast('Presentieregistratie opgeslagen en les afgesloten','success')});
    $$('[data-attendance-note]').forEach(b=>b.onclick=()=>openAttendanceNote(b.dataset.attendanceNote));

    $$('[data-new-grade]').forEach(b=>b.onclick=()=>openGradeEditor());
    $$('[data-edit-grade]').forEach(b=>b.onclick=()=>openGradeEditor(b.dataset.editGrade||null,{studentId:b.dataset.gradeStudent,title:b.dataset.gradeTitle}));
    $('[data-results-class]')?.addEventListener('change',e=>{SP.state.selectedClassId=e.target.value;SP.save();App.render()});
    $$('[data-grade-settings]').forEach(b=>b.onclick=()=>toast('Resultaatinstellingen geopend'));
    $$('[data-new-test-column]').forEach(b=>b.onclick=()=>openTestEditor());

    $$('[data-new-test]').forEach(b=>b.onclick=()=>openTestEditor());
    $$('[data-edit-test]').forEach(b=>b.onclick=()=>openTestEditor(b.dataset.editTest));
    $$('[data-new-assignment]').forEach(b=>b.onclick=()=>openAssignmentEditor());
    $$('[data-edit-assignment]').forEach(b=>b.onclick=()=>openAssignmentEditor(b.dataset.editAssignment));
    $$('[data-review-assignment]').forEach(b=>b.onclick=()=>reviewAssignment(b.dataset.reviewAssignment));
    $$('[data-message-missing]').forEach(b=>b.onclick=()=>toast('Herinnering naar ontbrekende leerlingen klaargezet','success'));

    $$('[data-new-guide]').forEach(b=>b.onclick=()=>openGuideEditor());
    $$('[data-edit-guide]').forEach(b=>b.onclick=()=>openGuideEditor(b.dataset.editGuide));
    $$('[data-add-guide-item]').forEach(b=>b.onclick=()=>openGuideItemEditor(b.dataset.addGuideItem));

    $$('[data-new-note]').forEach(b=>b.onclick=()=>openNoteEditor());
    $$('[data-edit-note]').forEach(b=>b.onclick=()=>openNoteEditor(b.dataset.editNote));
    $$('[data-new-message]').forEach(b=>b.onclick=()=>openTeacherMessage());
    $$('[data-new-message-to]').forEach(b=>b.onclick=()=>openTeacherMessage(b.dataset.newMessageTo));
    $$('[data-edit-teacher-message]').forEach(b=>b.onclick=()=>openTeacherMessage(null,b.dataset.editTeacherMessage));
    $$('[data-new-announcement]').forEach(b=>b.onclick=()=>openAnnouncementEditor());
    $$('[data-edit-announcement]').forEach(b=>b.onclick=()=>openAnnouncementEditor(b.dataset.editAnnouncement));

    $$('[data-export-report],[data-mentor-export]').forEach(b=>b.onclick=exportReport);
    $$('[data-generate-report]').forEach(b=>b.onclick=()=>toast('Nieuw rapport gegenereerd','success'));
    $$('[data-backup]').forEach(b=>b.onclick=backupData);
    $$('[data-restore]').forEach(b=>b.onclick=restoreData);
    $$('[data-reset-v3]').forEach(b=>b.onclick=resetData);
    $$('[data-edit-teacher-profile]').forEach(b=>b.onclick=openTeacherProfileEditor);
    $$('[data-upload-file]').forEach(b=>b.onclick=()=>toast('Bestandsupload is alleen een demo op GitHub Pages'));
    $$('[data-new-folder]').forEach(b=>b.onclick=()=>toast('Nieuwe map aangemaakt','success'));

    $$('[data-teacher-setting]').forEach(input=>input.onchange=()=>changeTeacherSetting(input));
    $$('[data-student-setting]').forEach(input=>input.onchange=()=>changeStudentSetting(input));
    $$('[data-notifications]').forEach(b=>b.onclick=openNotifications);
    $('[data-import-backup-input]')?.addEventListener('change',handleBackupFile);
  }

  function toggleTheme(){SP.state.theme=SP.state.theme==='dark'?'light':'dark';saveAndRender('Thema aangepast')}
  function toggleHomework(id){const h=SP.state.homework.find(x=>x.id===id);if(!h)return;h.done=!h.done;saveAndRender(h.done?'Huiswerk afgevinkt':'Huiswerk opnieuw geopend','success')}

  function openStudentMenu(){
    modal('Meer',`<div class="mobile-more-list">${SP.student.nav.slice(5).map(i=>`<button data-modal-page="${i.id}"><span>${U.icon(i.icon)}</span>${esc(i.label)}<i>›</i></button>`).join('')}<button data-modal-switch-teacher><span>↗</span>Docentenomgeving<i>›</i></button></div>`,{onOpen:(box,d)=>{box.querySelectorAll('[data-modal-page]').forEach(b=>b.onclick=()=>{d.close();App.goStudent(b.dataset.modalPage)});box.querySelector('[data-modal-switch-teacher]').onclick=()=>{d.close();App.switchRole('teacher')}}});
  }
  function openStudentSearch(){
    modal('Zoeken',`<div class="student-search-modal"><input autofocus placeholder="Zoek rooster, cijfers, berichten…" data-student-global-search><div data-search-results></div></div>`,{onOpen:box=>{const input=box.querySelector('[data-student-global-search]'),results=box.querySelector('[data-search-results]');const run=()=>{const q=input.value.toLowerCase().trim();const pages=SP.student.nav.filter(i=>i.label.toLowerCase().includes(q));const homework=SP.state.homework.filter(h=>`${h.subject} ${h.title}`.toLowerCase().includes(q)).slice(0,5);results.innerHTML=q?`${pages.map(p=>`<button data-result-page="${p.id}"><span>${U.icon(p.icon)}</span><strong>${esc(p.label)}</strong></button>`).join('')}${homework.map(h=>`<button data-result-page="guide"><span>✓</span><strong>${esc(h.subject)}</strong><small>${esc(h.title)}</small></button>`).join('')}`:'<p class="muted">Typ om te zoeken.</p>';results.querySelectorAll('[data-result-page]').forEach(b=>b.onclick=()=>{box.closest('dialog').close();App.goStudent(b.dataset.resultPage)})};input.oninput=run;run()}});
  }
  function sendStudentMessage(e){e.preventDefault();const input=e.currentTarget.elements.text,text=input.value.trim();if(!text)return;const conv=SP.state.conversations.find(c=>c.id===SP.state.selectedConversationId);conv.messages.push({id:SP.id('msg'),from:SP.state.profile.student.name,text,time:new Date().toISOString()});conv.unread=0;saveAndRender('Bericht verstuurd','success')}
  function openLessonInfo(id){const l=U.lessonById(id);if(!l)return;modal(l.subject,`<div class="lesson-detail-card"><div class="lesson-detail-time"><strong>${esc(l.start)}–${esc(l.end)}</strong><span>${esc(U.days[l.day])}</span></div><dl><div><dt>Lokaal</dt><dd>${esc(l.room)}</dd></div><div><dt>Docent</dt><dd>${esc(l.teacher)}</dd></div><div><dt>Klas</dt><dd>${esc(className(l.classId))}</dd></div><div><dt>Status</dt><dd>${esc(l.status||'Normaal')}</dd></div></dl></div>`)}

  function openCommandPalette(){
    const items=SP.teacher.navGroups.flatMap(g=>g.items);
    modal('Snel zoeken',`<div class="command-palette"><input autofocus placeholder="Zoek functie, leerling of klas…" data-command-input><div data-command-results></div></div>`,{wide:true,onOpen:(box,d)=>{const input=box.querySelector('[data-command-input]'),results=box.querySelector('[data-command-results]');const renderResults=()=>{const q=input.value.toLowerCase().trim();const pages=items.filter(i=>i.label.toLowerCase().includes(q)).slice(0,6);const students=SP.state.students.filter(s=>studentName(s).toLowerCase().includes(q)||s.number.includes(q)).slice(0,6);const classes=SP.state.classes.filter(c=>c.name.toLowerCase().includes(q)).slice(0,4);results.innerHTML=`${pages.length?'<span class="command-section">FUNCTIES</span>':''}${pages.map(p=>`<button data-command-page="${p.id}"><span>${U.icon(p.icon)}</span><span><strong>${esc(p.label)}</strong><small>Open pagina</small></span><kbd>↵</kbd></button>`).join('')}${students.length?'<span class="command-section">LEERLINGEN</span>':''}${students.map(s=>`<button data-command-student="${s.id}"><span class="student-avatar-xs">${esc(s.avatar)}</span><span><strong>${esc(studentName(s))}</strong><small>${esc(className(s.classId))} · ${esc(s.number)}</small></span><kbd>↵</kbd></button>`).join('')}${classes.length?'<span class="command-section">KLASSEN</span>':''}${classes.map(c=>`<button data-command-class="${c.id}"><span>♟</span><span><strong>${esc(c.name)}</strong><small>${esc(c.level)}</small></span></button>`).join('')}`;results.querySelectorAll('[data-command-page]').forEach(b=>b.onclick=()=>{d.close();App.goTeacher(b.dataset.commandPage)});results.querySelectorAll('[data-command-student]').forEach(b=>b.onclick=()=>{d.close();openStudentDrawer(b.dataset.commandStudent)});results.querySelectorAll('[data-command-class]').forEach(b=>b.onclick=()=>{SP.state.selectedClassId=b.dataset.commandClass;SP.save();d.close();App.goTeacher('students')})};input.oninput=renderResults;renderResults()}})
  }
  function openQuickCreate(){modal('Nieuw',`<div class="quick-create-menu"><button data-qc="student"><span>♙</span><strong>Leerling</strong><small>Nieuwe leerling aanmaken</small></button><button data-qc="lesson"><span>▦</span><strong>Afspraak</strong><small>Les of persoonlijke afspraak</small></button><button data-qc="grade"><span>7⁺</span><strong>Resultaat</strong><small>Cijfer invoeren</small></button><button data-qc="assignment"><span>▤</span><strong>Opdracht</strong><small>Nieuwe inleveropdracht</small></button><button data-qc="message"><span>✉</span><strong>Bericht</strong><small>Naar leerling, klas of ouders</small></button><button data-qc="note"><span>✎</span><strong>Notitie</strong><small>Mentor- of leerlingnotitie</small></button></div>`,{onOpen:(box,d)=>box.querySelectorAll('[data-qc]').forEach(b=>b.onclick=()=>{d.close();({student:openStudentEditor,lesson:openLessonEditor,grade:openGradeEditor,assignment:openAssignmentEditor,message:openTeacherMessage,note:openNoteEditor}[b.dataset.qc])()})})}
  function openTeacherMenu(){modal('Account',`<div class="account-menu"><div class="account-hero"><span class="teacher-avatar large">${esc(SP.state.profile.teacher.initials)}</span><div><strong>${esc(SP.state.profile.teacher.name)}</strong><small>${esc(SP.state.profile.teacher.email)}</small></div></div><button data-account-settings>⚙ Instellingen <i>›</i></button><button data-account-student>↗ Leerlingweergave <i>›</i></button></div>`,{onOpen:(box,d)=>{box.querySelector('[data-account-settings]').onclick=()=>{d.close();App.goTeacher('settings')};box.querySelector('[data-account-student]').onclick=()=>{d.close();App.switchRole('student')}}})}

  function openStudentEditor(id=null){
    const s=id?U.studentById(id):null;
    const content=`${field('Voornaam','firstName',s?.firstName||'',{required:true})}${field('Achternaam','lastName',s?.lastName||'',{required:true})}${field('Leerlingnummer','number',s?.number||nextNumber(),{required:true})}${selectField('Klas','classId',SP.state.classes.map(c=>({value:c.id,label:c.name})),s?.classId||SP.state.selectedClassId)}${field('E-mail','email',s?.email||'',{type:'email',required:true})}${field('Geboortedatum','birthDate',s?.birthDate||'',{type:'date'})}${field('Telefoon','phone',s?.phone||'')}${field('Mentor','mentor',s?.mentor||SP.state.profile.teacher.name)}${field('Naam verzorger','parent',s?.parent||'')}${field('E-mail verzorger','parentEmail',s?.parentEmail||'',{type:'email'})}${field('Tags','tags',s?.tags?.join(', ')||'',{full:true,placeholder:'bijv. dyslexie, extra aandacht'})}`;
    modal(s?'Leerling bewerken':'Nieuwe leerling aanmaken',form('',content,s?'Wijzigingen opslaan':'Leerling aanmaken'),{wide:true,onOpen:(box,d)=>{box.querySelector('[data-close-modal]').onclick=()=>d.close();box.querySelector('[data-modal-form]').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),firstName=String(fd.get('firstName')).trim(),lastName=String(fd.get('lastName')).trim();if(!firstName||!lastName)return;const data={firstName,lastName,number:String(fd.get('number')),classId:String(fd.get('classId')),email:String(fd.get('email')),birthDate:String(fd.get('birthDate')),phone:String(fd.get('phone')),mentor:String(fd.get('mentor')),parent:String(fd.get('parent')),parentEmail:String(fd.get('parentEmail')),tags:String(fd.get('tags')).split(',').map(x=>x.trim()).filter(Boolean),avatar:U.initials(`${firstName} ${lastName}`),status:'active'};if(s)Object.assign(s,data);else SP.state.students.push({id:SP.id('stu'),notes:'',...data});SP.audit(`${s?'Leerling gewijzigd':'Leerling aangemaakt'}: ${firstName} ${lastName}`);d.close();saveAndRender(s?'Leerling bijgewerkt':'Leerling aangemaakt','success')}}})
  }
  function openStudentDrawer(id){
    const s=U.studentById(id);if(!s)return;SP.state.selectedStudentId=id;SP.save();const avg=U.weightedAverage(id),att=U.attendanceCounts(id),grades=U.studentGrades(id).slice(0,5),notes=SP.state.notes.filter(n=>n.studentId===id).slice(0,3);
    modal(studentName(s),`<div class="student-drawer"><div class="student-drawer-head"><span class="profile-avatar large">${esc(s.avatar)}</span><div><h3>${esc(studentName(s))}</h3><p>${esc(className(s.classId))} · ${esc(s.number)} · ${esc(s.email)}</p><div>${s.tags?.map(t=>badge(t,'warning')).join(' ')||badge('Geen signalen','success')}</div></div></div><div class="student-drawer-kpis">${U.stat('Gemiddelde',avg?avg.toFixed(1).replace('.',','):'—','Alle vakken')}${U.stat('Te laat',String(att.late),'Registraties')}${U.stat('Afwezig',String(att.absent+att.excused),'Registraties')}</div><div class="student-drawer-tabs"><button class="active">Overzicht</button><button data-drawer-tab="grades">Resultaten</button><button data-drawer-tab="notes">Notities</button></div><section class="drawer-section"><h4>Laatste resultaten</h4>${grades.map(g=>`<div class="drawer-row"><span><strong>${esc(g.subject)}</strong><small>${esc(g.title)}</small></span><b class="table-grade ${U.gradeColor(g.grade)}">${g.grade.toFixed(1).replace('.',',')}</b></div>`).join('')||'<p class="muted">Geen resultaten.</p>'}</section><section class="drawer-section"><h4>Laatste notities</h4>${notes.map(n=>`<div class="drawer-note"><strong>${dateNL(n.date)}</strong><p>${esc(n.text)}</p></div>`).join('')||'<p class="muted">Geen notities.</p>'}</section><div class="modal-actions"><button class="btn danger" data-delete-student="${s.id}">Verwijderen</button><button class="btn teacher-secondary" data-drawer-note="${s.id}">＋ Notitie</button><button class="btn teacher-primary" data-drawer-edit="${s.id}">Leerling bewerken</button></div></div>`,{wide:true,onOpen:(box,d)=>{box.querySelector('[data-drawer-edit]').onclick=()=>{d.close();openStudentEditor(id)};box.querySelector('[data-drawer-note]').onclick=()=>{d.close();openNoteEditor(null,id)};box.querySelector('[data-delete-student]').onclick=()=>confirmAction(`Leerling ${studentName(s)} verwijderen?`,()=>{SP.state.students=SP.state.students.filter(x=>x.id!==id);SP.audit(`Leerling verwijderd: ${studentName(s)}`);d.close();saveAndRender('Leerling verwijderd')})}})
  }
  function openStudentActions(id){modal('Leerlingacties',`<div class="action-list"><button data-sa="open">Open leerling</button><button data-sa="edit">Bewerken</button><button data-sa="grade">Resultaat invoeren</button><button data-sa="note">Notitie toevoegen</button><button data-sa="move">Naar andere klas</button></div>`,{onOpen:(box,d)=>box.querySelectorAll('[data-sa]').forEach(b=>b.onclick=()=>{d.close();if(b.dataset.sa==='open')openStudentDrawer(id);if(b.dataset.sa==='edit')openStudentEditor(id);if(b.dataset.sa==='grade')openGradeEditor(null,{studentId:id});if(b.dataset.sa==='note')openNoteEditor(null,id);if(b.dataset.sa==='move')openMoveStudent(id)})})}
  function openMoveStudent(id){const s=U.studentById(id);modal('Leerling verplaatsen',form('',selectField('Nieuwe klas','classId',SP.state.classes.map(c=>({value:c.id,label:c.name})),s.classId),'Verplaatsen'),{onOpen:(box,d)=>{box.querySelector('[data-close-modal]').onclick=()=>d.close();box.querySelector('form').onsubmit=e=>{e.preventDefault();s.classId=new FormData(e.currentTarget).get('classId');SP.audit(`${studentName(s)} verplaatst naar ${className(s.classId)}`);d.close();saveAndRender('Leerling verplaatst','success')}}})}
  function filterStudentTable(e){const q=e.target.value.toLowerCase();$$('[data-student-row]').forEach(row=>row.hidden=!row.dataset.searchText.includes(q))}

  function openClassEditor(id=null){const c=id?U.classById(id):null;const content=`${field('Klasnaam','name',c?.name||'',{required:true})}${selectField('Niveau','level',['Mavo','Kader','Basis','Havo','Vwo'],c?.level||'Mavo')}${field('Leerjaar','year',c?.year||3,{type:'number',min:1,max:6})}${field('Vak','subject',c?.subject||'Nederlands')}${field('Mentor','mentor',c?.mentor||SP.state.profile.teacher.name,{full:true})}`;modal(c?'Klas bewerken':'Nieuwe klas',form('',content,c?'Opslaan':'Klas aanmaken'),{onOpen:(box,d)=>{box.querySelector('[data-close-modal]').onclick=()=>d.close();box.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),data={name:String(fd.get('name')),level:String(fd.get('level')),year:Number(fd.get('year')),subject:String(fd.get('subject')),mentor:String(fd.get('mentor')),color:c?.color||'#0f74bd'};if(c)Object.assign(c,data);else SP.state.classes.push({id:SP.id('cls'),...data});SP.audit(`${c?'Klas gewijzigd':'Klas aangemaakt'}: ${data.name}`);d.close();saveAndRender('Klas opgeslagen','success')}}})}

  function openLessonEditor(id=null,preset={}){const existing=id?U.lessonById(id):null;const l=existing||{day:preset.day||1,start:preset.start||'08:30',end:'09:20',subject:'Nederlands',classId:SP.state.selectedClassId||'cls_3m2',room:'B1.14',teacher:SP.state.profile.teacher.name,type:'lesson',studentVisible:true,status:'normal'};const content=`${selectField('Dag','day',[1,2,3,4,5].map(v=>({value:v,label:U.days[v]})),l.day)}${selectField('Type','type',[{value:'lesson',label:'Les'},{value:'mentor',label:'Mentoruur'},{value:'meeting',label:'Afspraak / overleg'}],l.type)}${field('Start','start',l.start,{type:'time',required:true})}${field('Einde','end',l.end,{type:'time',required:true})}${field('Titel / vak','subject',l.subject,{required:true})}${selectField('Klas','classId',[{value:'',label:'Geen klas'},...SP.state.classes.map(c=>({value:c.id,label:c.name}))],l.classId||'')}${field('Lokaal','room',l.room)}${selectField('Status','status',[{value:'normal',label:'Normaal'},{value:'changed',label:'Gewijzigd'},{value:'cancelled',label:'Uitgevallen'}],l.status||'normal')}`;const extra=existing?`<button type="button" class="btn danger" data-delete-lesson>Verwijderen</button>`:'';modal(existing?'Afspraak bewerken':'Nieuwe afspraak',form('',content,'Opslaan',extra),{onOpen:(box,d)=>{box.querySelector('[data-close-modal]').onclick=()=>d.close();box.querySelector('[data-delete-lesson]')?.addEventListener('click',()=>confirmAction('Deze afspraak verwijderen?',()=>{SP.state.schedule=SP.state.schedule.filter(x=>x.id!==id);SP.state.personalSchedule=SP.state.personalSchedule.filter(x=>x.id!==id);SP.audit('Roosteritem verwijderd');d.close();saveAndRender('Afspraak verwijderd')}));box.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),data={day:Number(fd.get('day')),type:String(fd.get('type')),start:String(fd.get('start')),end:String(fd.get('end')),subject:String(fd.get('subject')),classId:String(fd.get('classId'))||null,room:String(fd.get('room')),teacher:SP.state.profile.teacher.name,status:String(fd.get('status')),studentVisible:String(fd.get('type'))!=='meeting'};if(existing)Object.assign(existing,data);else{const item={id:SP.id('les'),...data};if(data.type==='meeting')SP.state.personalSchedule.push(item);else SP.state.schedule.push(item)}SP.audit(`${existing?'Roosteritem gewijzigd':'Roosteritem toegevoegd'}: ${data.subject}`);d.close();saveAndRender('Rooster bijgewerkt','success')}}})}
  function bindDragDrop(){let dragged=null;$$('[data-drag-lesson]').forEach(el=>{el.ondragstart=()=>{dragged=el.dataset.dragLesson;el.classList.add('dragging')};el.ondragend=()=>el.classList.remove('dragging')});$$('.teacher-slot').forEach(slot=>{slot.ondragover=e=>{e.preventDefault();slot.classList.add('drag-over')};slot.ondragleave=()=>slot.classList.remove('drag-over');slot.ondrop=e=>{e.preventDefault();slot.classList.remove('drag-over');const l=U.lessonById(dragged);if(!l)return;l.day=Number(slot.dataset.slotDay);l.start=slot.dataset.slotTime;const [h,m]=l.start.split(':').map(Number);const endMin=h*60+m+50;l.end=`${String(Math.floor(endMin/60)).padStart(2,'0')}:${String(endMin%60).padStart(2,'0')}`;SP.audit(`Roosteritem verplaatst: ${l.subject}`);saveAndRender('Afspraak verplaatst','success')}})}

  function handleAttendanceButton(e){const wrap=e.currentTarget.closest('[data-attendance-student]'),studentId=wrap.dataset.attendanceStudent,status=e.currentTarget.dataset.setAttendance,date='2026-08-26';let a=SP.state.attendance.find(x=>x.studentId===studentId&&x.date===date);if(!a){a={id:SP.id('att'),studentId,lessonId:'les_010',date,status,minutes:status==='late'?5:status==='present'?0:50,note:''};SP.state.attendance.push(a)}else{a.status=status;a.minutes=status==='late'?5:status==='present'?0:50}SP.save();App.render()}
  function markAllPresent(){const classId=SP.state.selectedClassId||'cls_3m2',date='2026-08-26';SP.state.students.filter(s=>s.classId===classId).forEach(s=>{let a=SP.state.attendance.find(x=>x.studentId===s.id&&x.date===date);if(a){a.status='present';a.minutes=0}else SP.state.attendance.push({id:SP.id('att'),studentId:s.id,lessonId:'les_010',date,status:'present',minutes:0,note:''})});saveAndRender('Iedereen op aanwezig gezet','success')}
  function openAttendanceNote(studentId){const date='2026-08-26';let a=SP.state.attendance.find(x=>x.studentId===studentId&&x.date===date);if(!a){a={id:SP.id('att'),studentId,lessonId:'les_010',date,status:'present',minutes:0,note:''};SP.state.attendance.push(a)}modal(`Notitie · ${studentName(U.studentById(studentId))}`,form('',textareaField('Opmerking','note',a.note,'Optionele toelichting'),'Opslaan'),{onOpen:(box,d)=>{box.querySelector('[data-close-modal]').onclick=()=>d.close();box.querySelector('form').onsubmit=e=>{e.preventDefault();a.note=String(new FormData(e.currentTarget).get('note'));d.close();saveAndRender('Presentienotitie opgeslagen','success')}}})}

  function openGradeEditor(id=null,preset={}){const g=id?SP.state.grades.find(x=>x.id===id):null;const classId=SP.state.selectedClassId||'cls_3m2';const students=SP.state.students.filter(s=>s.classId===classId);const selected=preset.studentId||g?.studentId||students[0]?.id;const content=`${selectField('Leerling','studentId',students.map(s=>({value:s.id,label:studentName(s)})),selected)}${field('Vak','subject',g?.subject||'Nederlands',{required:true})}${field('Onderdeel','title',preset.title||g?.title||'Leesvaardigheid',{required:true})}${field('Cijfer','grade',g?.grade||'',{type:'number',min:1,max:10,step:0.1,required:true})}${field('Weging','weight',g?.weight||1,{type:'number',min:1,max:10})}${field('Datum','date',g?.date||'2026-08-26',{type:'date'})}`;const extra=g?'<button type="button" class="btn danger" data-delete-grade>Verwijderen</button>':'';modal(g?'Resultaat bewerken':'Resultaat invoeren',form('',content,'Opslaan',extra),{onOpen:(box,d)=>{box.querySelector('[data-close-modal]').onclick=()=>d.close();box.querySelector('[data-delete-grade]')?.addEventListener('click',()=>confirmAction('Resultaat verwijderen?',()=>{SP.state.grades=SP.state.grades.filter(x=>x.id!==g.id);SP.audit('Resultaat verwijderd');d.close();saveAndRender('Resultaat verwijderd')}));box.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),data={studentId:String(fd.get('studentId')),subject:String(fd.get('subject')),title:String(fd.get('title')),grade:Number(fd.get('grade')),weight:Number(fd.get('weight'))||1,date:String(fd.get('date'))};if(data.grade<1||data.grade>10)return toast('Cijfer moet tussen 1 en 10 liggen','error');if(g)Object.assign(g,data);else SP.state.grades.push({id:SP.id('gr'),...data});SP.audit(`${g?'Resultaat gewijzigd':'Resultaat ingevoerd'}: ${studentName(U.studentById(data.studentId))}`);d.close();saveAndRender('Resultaat opgeslagen','success')}}})}
  function openTestEditor(id=null){const t=id?SP.state.tests.find(x=>x.id===id):null;const content=`${field('Titel','title',t?.title||'',{required:true})}${field('Vak','subject',t?.subject||'Nederlands',{required:true})}${field('Datum','date',t?.date||'2026-09-03',{type:'date',required:true})}${field('Weging','weight',t?.weight||1,{type:'number',min:1,max:10})}${selectField('Lesgroep','classId',SP.state.classes.map(c=>({value:c.id,label:c.name})),t?.classIds?.[0]||SP.state.selectedClassId)}${selectField('Status','published',[{value:'true',label:'Gepubliceerd'},{value:'false',label:'Concept'}],String(t?.published??true))}`;const extra=t?'<button type="button" class="btn danger" data-delete-test>Verwijderen</button>':'';modal(t?'Toets bewerken':'Toets inplannen',form('',content,'Opslaan',extra),{onOpen:(box,d)=>{box.querySelector('[data-close-modal]').onclick=()=>d.close();box.querySelector('[data-delete-test]')?.addEventListener('click',()=>confirmAction('Toets verwijderen?',()=>{SP.state.tests=SP.state.tests.filter(x=>x.id!==t.id);d.close();saveAndRender('Toets verwijderd')}));box.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),data={title:String(fd.get('title')),subject:String(fd.get('subject')),date:String(fd.get('date')),weight:Number(fd.get('weight'))||1,classIds:[String(fd.get('classId'))],published:String(fd.get('published'))==='true'};if(t)Object.assign(t,data);else SP.state.tests.push({id:SP.id('test'),...data});SP.audit(`${t?'Toets gewijzigd':'Toets ingepland'}: ${data.title}`);d.close();saveAndRender('Toets opgeslagen','success')}}})}

  function openAssignmentEditor(id=null){const a=id?SP.state.assignments.find(x=>x.id===id):null;const content=`${field('Titel','title',a?.title||'',{required:true})}${selectField('Klas','classId',SP.state.classes.map(c=>({value:c.id,label:c.name})),a?.classId||SP.state.selectedClassId)}${field('Vak','subject',a?.subject||'Nederlands')}${field('Deadline','due',a?.due||'2026-09-04',{type:'date'})}${textareaField('Instructies','instructions',a?.instructions||'','Beschrijf de opdracht…')}${selectField('Status','published',[{value:'true',label:'Gepubliceerd'},{value:'false',label:'Concept'}],String(a?.published??true))}`;const extra=a?'<button type="button" class="btn danger" data-delete-assignment>Verwijderen</button>':'';modal(a?'Opdracht bewerken':'Nieuwe opdracht',form('',content,'Opslaan',extra),{wide:true,onOpen:(box,d)=>{box.querySelector('[data-close-modal]').onclick=()=>d.close();box.querySelector('[data-delete-assignment]')?.addEventListener('click',()=>confirmAction('Opdracht verwijderen?',()=>{SP.state.assignments=SP.state.assignments.filter(x=>x.id!==a.id);d.close();saveAndRender('Opdracht verwijderd')}));box.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),classId=String(fd.get('classId')),total=SP.state.students.filter(s=>s.classId===classId).length||26,data={title:String(fd.get('title')),classId,subject:String(fd.get('subject')),due:String(fd.get('due')),instructions:String(fd.get('instructions')),published:String(fd.get('published'))==='true',submitted:a?.submitted||0,total};if(a)Object.assign(a,data);else SP.state.assignments.push({id:SP.id('as'),...data});SP.audit(`${a?'Opdracht gewijzigd':'Opdracht gemaakt'}: ${data.title}`);d.close();saveAndRender('Opdracht opgeslagen','success')}}})}
  function reviewAssignment(id){const a=SP.state.assignments.find(x=>x.id===id);if(!a)return;modal(`Nakijken · ${a.title}`,`<div class="review-demo"><div class="review-paper"><span>Inlevering 1 van ${a.submitted}</span><h3>Boekverslag — voorbeeldinlevering</h3><p>Dit is een demonstratie van de nakijkweergave. In een echte backend zou hier het ingeleverde bestand of antwoord staan.</p><textarea placeholder="Feedback voor leerling"></textarea><div class="review-score"><label>Beoordeling <input type="number" min="1" max="10" step="0.1" value="7.5"></label></div></div><div class="modal-actions"><button class="btn teacher-secondary" data-review-next>Overslaan</button><button class="btn teacher-primary" data-review-save>Opslaan & volgende</button></div></div>`,{wide:true,onOpen:(box,d)=>{box.querySelector('[data-review-next]').onclick=()=>toast('Volgende inlevering');box.querySelector('[data-review-save]').onclick=()=>{a.submitted=Math.max(0,a.submitted-1);d.close();saveAndRender('Feedback opgeslagen','success')}}})}

  function openGuideEditor(id=null){const g=id?SP.state.studyGuides.find(x=>x.id===id):null;const content=`${field('Titel','title',g?.title||'',{required:true})}${field('Vak','subject',g?.subject||'Nederlands')}${selectField('Lesgroep','classId',SP.state.classes.map(c=>({value:c.id,label:c.name})),g?.classIds?.[0]||SP.state.selectedClassId)}${field('Voortgang %','progress',g?.progress||0,{type:'number',min:0,max:100})}${selectField('Status','published',[{value:'true',label:'Gepubliceerd'},{value:'false',label:'Concept'}],String(g?.published??true))}`;modal(g?'Studiewijzer bewerken':'Nieuwe studiewijzer',form('',content,'Opslaan'),{onOpen:(box,d)=>{box.querySelector('[data-close-modal]').onclick=()=>d.close();box.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),data={title:String(fd.get('title')),subject:String(fd.get('subject')),classIds:[String(fd.get('classId'))],progress:Number(fd.get('progress'))||0,published:String(fd.get('published'))==='true'};if(g)Object.assign(g,data);else SP.state.studyGuides.push({id:SP.id('guide'),items:[],...data});SP.audit(`${g?'Studiewijzer gewijzigd':'Studiewijzer gemaakt'}: ${data.title}`);d.close();saveAndRender('Studiewijzer opgeslagen','success')}}})}
  function openGuideItemEditor(guideId){const g=SP.state.studyGuides.find(x=>x.id===guideId);modal('Onderdeel toevoegen',form('',`${selectField('Type','type',[{value:'homework',label:'Huiswerk'},{value:'material',label:'Lesmateriaal'},{value:'test',label:'Toets'}],'homework')}${field('Titel','title','',{required:true})}${field('Datum','date','2026-09-01',{type:'date'})}`,'Toevoegen'),{onOpen:(box,d)=>{box.querySelector('[data-close-modal]').onclick=()=>d.close();box.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget);g.items.push({id:SP.id('gi'),type:String(fd.get('type')),title:String(fd.get('title')),date:String(fd.get('date')),done:false});d.close();saveAndRender('Onderdeel toegevoegd','success')}}})}

  function openNoteEditor(id=null,presetStudent=null){const n=id?SP.state.notes.find(x=>x.id===id):null;const selected=presetStudent||n?.studentId||SP.state.selectedStudentId;const content=`${selectField('Leerling','studentId',SP.state.students.map(s=>({value:s.id,label:`${studentName(s)} · ${className(s.classId)}`})),selected)}${selectField('Categorie','category',['mentor','positief','gesprek','zorg','afspraak'],n?.category||'mentor')}${field('Datum','date',n?.date||'2026-08-26',{type:'date'})}${textareaField('Notitie','text',n?.text||'','Schrijf je notitie…')}${selectField('Zichtbaarheid','private',[{value:'true',label:'Privé'},{value:'false',label:'Gedeeld'}],String(n?.private??true))}`;modal(n?'Notitie bewerken':'Nieuwe notitie',form('',content,'Opslaan'),{wide:true,onOpen:(box,d)=>{box.querySelector('[data-close-modal]').onclick=()=>d.close();box.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),data={studentId:String(fd.get('studentId')),category:String(fd.get('category')),date:String(fd.get('date')),text:String(fd.get('text')),private:String(fd.get('private'))==='true',author:SP.state.profile.teacher.name};if(n)Object.assign(n,data);else SP.state.notes.unshift({id:SP.id('note'),...data});SP.audit(`Notitie ${n?'gewijzigd':'toegevoegd'} voor ${studentName(U.studentById(data.studentId))}`);d.close();saveAndRender('Notitie opgeslagen','success')}}})}

  function openTeacherMessage(to='',id=null){const m=id?SP.state.teacherMessages.find(x=>x.id===id):null;const content=`${field('Aan','to',to||m?.to||'',{required:true})}${field('Onderwerp','subject',m?.subject||'',{required:true})}${textareaField('Bericht','body',m?.body||'','Schrijf je bericht…')}${selectField('Status','status',[{value:'sent',label:'Direct versturen'},{value:'draft',label:'Opslaan als concept'}],m?.status||'sent')}`;modal(m?'Bericht bewerken':'Nieuw bericht',form('',content,m?'Opslaan':'Versturen'),{wide:true,onOpen:(box,d)=>{box.querySelector('[data-close-modal]').onclick=()=>d.close();box.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),data={to:String(fd.get('to')),subject:String(fd.get('subject')),body:String(fd.get('body')),status:String(fd.get('status')),date:'2026-08-26'};if(m)Object.assign(m,data);else SP.state.teacherMessages.unshift({id:SP.id('tm'),...data});SP.audit(`Bericht ${data.status==='sent'?'verstuurd':'opgeslagen'}: ${data.subject}`);d.close();saveAndRender(data.status==='sent'?'Bericht verstuurd':'Concept opgeslagen','success')}}})}
  function openAnnouncementEditor(id=null){const a=id?SP.state.announcements.find(x=>x.id===id):null;const content=`${field('Titel','title',a?.title||'',{required:true})}${selectField('Doelgroep','audience',[{value:'all',label:'Iedereen'},{value:'students',label:'Leerlingen'},{value:'teachers',label:'Docenten'}],a?.audience||'all')}${textareaField('Bericht','body',a?.body||'','Mededeling…')}`;modal(a?'Mededeling bewerken':'Nieuwe mededeling',form('',content,'Publiceren'),{onOpen:(box,d)=>{box.querySelector('[data-close-modal]').onclick=()=>d.close();box.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget),data={title:String(fd.get('title')),audience:String(fd.get('audience')),body:String(fd.get('body')),date:'2026-08-26',published:true};if(a)Object.assign(a,data);else SP.state.announcements.unshift({id:SP.id('ann'),...data});d.close();saveAndRender('Mededeling gepubliceerd','success')}}})}

  function exportStudents(){const rows=[['leerlingnummer','voornaam','achternaam','klas','email'],...SP.state.students.map(s=>[s.number,s.firstName,s.lastName,className(s.classId),s.email])];download('schoolportal-leerlingen.csv',rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv');toast('Leerlingen geëxporteerd','success')}
  function openImportStudents(){modal('Leerlingen importeren',`<div class="import-box"><div class="drop-zone"><strong>CSV import-demo</strong><p>Plak hieronder regels in het formaat: voornaam, achternaam, klas, e-mail</p><textarea data-import-text placeholder="Piet, Jansen, 3M2, piet@school.nl"></textarea></div><div class="modal-actions"><button class="btn ghost" data-close-modal>Annuleren</button><button class="btn teacher-primary" data-run-import>Importeren</button></div></div>`,{wide:true,onOpen:(box,d)=>{box.querySelector('[data-close-modal]').onclick=()=>d.close();box.querySelector('[data-run-import]').onclick=()=>{const lines=box.querySelector('[data-import-text]').value.split('\n').map(x=>x.trim()).filter(Boolean);let count=0;for(const line of lines){const [firstName,lastName,classText,email]=line.split(',').map(x=>x.trim());if(!firstName||!lastName)continue;const cls=SP.state.classes.find(c=>c.name.toLowerCase()===String(classText).toLowerCase())||SP.state.classes[0];SP.state.students.push({id:SP.id('stu'),firstName,lastName,classId:cls.id,number:nextNumber(),email:email||`${firstName}.${lastName}@school.nl`.toLowerCase(),birthDate:'',status:'active',mentor:cls.mentor,phone:'',parent:'',parentEmail:'',tags:[],notes:'',avatar:U.initials(`${firstName} ${lastName}`)});count++}SP.audit(`${count} leerlingen geïmporteerd`);d.close();saveAndRender(`${count} leerlingen geïmporteerd`,'success')}}})}
  function exportReport(){const classId=SP.state.selectedClassId,students=SP.state.students.filter(s=>s.classId===classId);const rows=[['naam','klas','gemiddelde','te_laat','afwezig'],...students.map(s=>{const a=U.attendanceCounts(s.id);return[studentName(s),className(s.classId),(U.weightedAverage(s.id)||0).toFixed(1),a.late,a.absent+a.excused]})];download('schoolportal-rapport.csv',rows.map(r=>r.join(',')).join('\n'),'text/csv');toast('Rapport geëxporteerd','success')}
  function backupData(){download('schoolportal-backup.json',JSON.stringify(SP.state,null,2));toast('Back-up gedownload','success')}
  function restoreData(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=handleBackupFile;input.click()}
  function handleBackupFile(e){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(data.version!==3)throw new Error('Verkeerde versie');SP.state=data;SP.save();App.render();toast('Back-up hersteld','success')}catch{toast('Ongeldige back-up','error')}};reader.readAsText(file)}
  function resetData(){confirmAction('Alle lokale wijzigingen wissen en demo-data herstellen?',()=>{SP.reset();App.render();toast('Demo-data hersteld','success')})}
  function openTeacherProfileEditor(){const p=SP.state.profile.teacher;modal('Profiel bewerken',form('',`${field('Naam','name',p.name,{required:true})}${field('E-mail','email',p.email,{type:'email'})}${field('Vak','subject',p.subject)}${field('Personeelsnummer','employeeNumber',p.employeeNumber)}`,'Opslaan'),{onOpen:(box,d)=>{box.querySelector('[data-close-modal]').onclick=()=>d.close();box.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.currentTarget);p.name=String(fd.get('name'));p.email=String(fd.get('email'));p.subject=String(fd.get('subject'));p.employeeNumber=String(fd.get('employeeNumber'));p.initials=U.initials(p.name);d.close();saveAndRender('Profiel bijgewerkt','success')}}})}

  function changeTeacherSetting(input){if(input.dataset.teacherSetting==='theme')SP.state.theme=input.checked?'dark':'light';if(input.dataset.teacherSetting==='dense')SP.state.settings.teacherDenseTables=input.checked;if(input.dataset.teacherSetting==='quick')SP.state.settings.teacherQuickActions=input.checked;saveAndRender('Instelling opgeslagen')}
  function changeStudentSetting(input){if(input.dataset.studentSetting==='theme')SP.state.theme=input.checked?'dark':'light';if(input.dataset.studentSetting==='notifications')SP.state.settings.studentNotifications=input.checked;if(input.dataset.studentSetting==='gradeColors')SP.state.settings.studentGradeColors=input.checked;saveAndRender('Instelling opgeslagen')}
  function openNotifications(){modal('Meldingen',`<div class="notification-list"><article><span class="notif-dot"></span><div><strong>2 lessen nog afsluiten</strong><p>Presentieregistratie ontbreekt.</p><small>Vandaag</small></div></article><article><span class="notif-dot purple"></span><div><strong>12 nieuwe inleveringen</strong><p>Boekverslag · 3M2</p><small>1 uur geleden</small></div></article><article><span class="notif-dot green"></span><div><strong>Rooster bijgewerkt</strong><p>Teamoverleg is verplaatst.</p><small>Gisteren</small></div></article></div>`)}

  document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(SP.state.role==='teacher')openCommandPalette();else openStudentSearch()}if(e.key==='Escape')$('#modal')?.close()});
  App.render();
})();